# Generated by Django 3.2.20 on 2023-07-10 16:26

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createceramics', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'date', 'time', 'service')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
    ]
